### ISSUE TITLE
Create Registration Form UI

### ISSUE THREAD

**Issue by misalima** [misalima/my-budget-planner-frontend#3]
> Issue related to User Story #5 
![image](https://github.com/user-attachments/assets/b26cb351-d086-48f3-b0a9-9f1c03583b32)

Follow the prototype design and implement the registration page and form using React, Tailwind CSS, and TypeScript. 

### Tasks:
- [ ] Implement the page to be displayed in the route `/register`
- [ ] Create form fields for first name, last name, email, password and password confirmation.
- [ ] Add client-side validation (e.g., required fields, password length) using `react-hook-form.`
- [ ] Although it's not in the prototype, add the NavBar menu to the page.
